export const data = {
  products: [
    {
      id: '1',
      name: '핑크 폴로 셔츠',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      id: '2',
      name: 'Marl Polo Shir',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 0,
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '3',
      name: '슬림 핏 셔츠',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      id: '4',
      name: '오랜지 Polo Shirt',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: '멋쟁이 신사들을 위한 셔츠',
    },
    {
      id: '5',
      name: '핑크 폴로 셔츠',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      id: '6',
      name: 'Marl Polo Shir',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 6,
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '7',
      name: '슬림 핏 셔츠',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 8,
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      id: '8',
      name: 'Orange Polo Shirt',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 13,
      rating: 4.5,
      numReviews: 10,
      description: '멋쟁이 신사들을 위한 셔츠',
    },
  ],
}
